baseURL = "http://home.ustc.edu.cn/~xys201821"
#relativeURLs = true
#uglyURLs = true
languageCode = 'en-us'
title = 'xYs Homepage'
theme = "hugo-coder"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Yan Su"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Yan Su's personal website"
keywords = "blog,developer,personal"
info = [" Undergraduate from USTC", "Majoring in Statistics"]
avatarURL = "images/avatar.png"
#gravatar = "john.doe@example.com"
since = 2022
katex = true
math = true
# Git Commit in Footer, uncomment the line below to enable it
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["css/page.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://www.bilibili.com/video/BV1GJ411x7h7"

[[params.social]]
name = "Youtube"
icon = "fa fa-2x fa-youtube"
weight = 6
url = "https://www.bilibili.com/video/BV1GJ411x7h7"

[[params.social]]
name = "Wechat"
icon = "fa fa-2x fa-wechat"
weight = 2
url = "https://www.bilibili.com/video/BV1GJ411x7h7"

[[params.social]]
name = "Steam"
icon = "fa fa-2x fa-steam-square"
weight = 3
url = "https://steamcommunity.com/profiles/76561198810460771/"

[[params.social]]
name = "Nintendo"
icon = "fa fa-2x fa-gamepad"
weight = 4
url = "https://www.bilibili.com/video/BV1GJ411x7h7"

[[params.social]]
name = "qq"
icon = "fa fa-2x fa-qq"
weight = 5
url = "https://www.bilibili.com/video/BV1GJ411x7h7"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Home"
weight = 1
url = "http://home.ustc.edu.cn/~xys201821/home/"

[[languages.en.menu.main]]
name = "Curriculum Vitae"
weight = 2
url = "http://home.ustc.edu.cn/~xys201821/cv/"

[[languages.en.menu.main]]
name = "Education"
weight = 3
url = "http://home.ustc.edu.cn/~xys201821/education/"

[[languages.en.menu.main]]
name = "Blog"
weight = 5
url = "http://home.ustc.edu.cn/~xys201821/posts/"

